locations = ['usa', 'japan', 'australia', 'hawaii']
print(locations)
print(sorted(locations))
print(locations)
locations.reverse()
print(locations)
locations.reverse()
print(locations)
locations.sort()
print(locations)
locations.sort(reverse=True)
print(locations)

locations = ['usa', 'japan', 'australia', 'hawaii']
locations.insert(0, 'dubai')
print(locations)
locations.append('italy')
print(locations)
locations.remove('italy')
print(locations)
print(sorted(locations))
print(locations)
locations.sort()
print(locations)
locations.sort(reverse=True)
print(locations)
pop_locations = locations.pop()
print(locations)
print(pop_locations)
print(len(locations))
